#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
