#!/usr/bin/env bash
# configure your Ngnix server so that /redirect_me is redirecting to another page
sudo apt-get update &&
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "301 Moved Permanently" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default 
sudo service nginx start
